package com.pf.dllo.food.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pf.dllo.food.db.CollectBean;
import com.pf.dllo.food.db.SearchBean;

import com.pf.dllo.food.db.CollectBeanDao;
import com.pf.dllo.food.db.SearchBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectBeanDaoConfig;
    private final DaoConfig searchBeanDaoConfig;

    private final CollectBeanDao collectBeanDao;
    private final SearchBeanDao searchBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectBeanDaoConfig = daoConfigMap.get(CollectBeanDao.class).clone();
        collectBeanDaoConfig.initIdentityScope(type);

        searchBeanDaoConfig = daoConfigMap.get(SearchBeanDao.class).clone();
        searchBeanDaoConfig.initIdentityScope(type);

        collectBeanDao = new CollectBeanDao(collectBeanDaoConfig, this);
        searchBeanDao = new SearchBeanDao(searchBeanDaoConfig, this);

        registerDao(CollectBean.class, collectBeanDao);
        registerDao(SearchBean.class, searchBeanDao);
    }
    
    public void clear() {
        collectBeanDaoConfig.clearIdentityScope();
        searchBeanDaoConfig.clearIdentityScope();
    }

    public CollectBeanDao getCollectBeanDao() {
        return collectBeanDao;
    }

    public SearchBeanDao getSearchBeanDao() {
        return searchBeanDao;
    }

}
